name: build-push-al2022

on:
  workflow_dispatch:
    inputs:
      push:
        description: Push the image to ghcr.io
        required: false
        default: true
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "vscode/devcontainers/al2022"

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: docker/setup-buildx-action@v2

      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
          tags: |
            latest
            ${{ github.event.inputs.UBUNTU_VERSION }}
          labels: |
            org.opencontainers.image.title=AL2022 devcontainer
            org.opencontainers.image.description=VS Code devcontainer: Amazon Linux 2022

      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          context: '{{defaultContext}}:devcontainers/al2022'
          push: ${{ github.event.inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

