name: build-push-ubuntu

on:
  workflow_dispatch:
    inputs:
      UBUNTU_VERSION:
        description: Ubuntu version of base image
        required: false
        default: 20.04
      push:
        description: Push the image to ghcr.io
        required: false
        default: true
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "vscode/devcontainers/ubuntu"

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: docker/setup-buildx-action@v1

      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
          tags: |
            latest
            ${{ github.event.inputs.UBUNTU_VERSION }}
          labels: |
            org.opencontainers.image.title=Ubuntu devcontainer
            org.opencontainers.image.description=VS Code devcontainer: Ubuntu ${{ github.event.inputs.UBUNTU_VERSION }}

      - uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          context: '{{defaultContext}}:devcontainers/ubuntu'
          push: ${{ github.event.inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            UBUNTU_VERSION=${{ github.event.inputs.UBUNTU_VERSION }}

